"""Run one Hermes Agent gateway per agent on the same host as general-chat.

The supervisor owns the whole lifecycle of an agent's Hermes profile:
render the minimal profile (``hermes_profile``), start its gateway, wait
for health, restart it when the rendered profile changed, stop it when the
agent leaves the Hermes runtime. Two backends:

- ``process`` — local development: a ``hermes gateway run`` child process
  per agent, ``HERMES_HOME`` = the agent's profile dir, loopback port.
- ``docker`` — deployed: one long-running sibling container per agent via
  the docker CLI (the same socket the MCP servers are spawned through).
  Each container mounts only its own profile dir, joins a dedicated network
  under the alias ``hermes-<agent>``, and never gets the docker socket.

Credentials never touch the profile on disk from here: the LLM key and any
MCP secrets are handed to the gateway as process/container environment
(``docker run -e NAME`` passthrough — values are not in argv), and the
per-agent ``API_SERVER_KEY`` is generated by ``write_profile`` and read
back from that agent's own ``.env``.
"""

from __future__ import annotations

import contextlib
import hashlib
import json
import logging
import os
import shutil
import socket
import subprocess
import threading
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import requests

from general_chat.hermes_profile import (
    CONTAINER_API_HOST,
    DEFAULT_API_PORT,
    HermesProfileSpec,
    validate_spec,
    write_profile,
)

logger = logging.getLogger(__name__)

BACKEND_PROCESS = "process"
BACKEND_DOCKER = "docker"
BACKENDS = (BACKEND_PROCESS, BACKEND_DOCKER)
DEFAULT_DOCKER_IMAGE = "hermes-agent:v2026.9.14"
DEFAULT_DOCKER_NETWORK = "openbench-hermes"
RENDER_HASH_FILE = ".sss-render.sha256"
_LOOPBACK = "127.0.0.1"


class HermesSupervisorError(RuntimeError):
    """Raised when a managed Hermes gateway cannot be started."""


@dataclass(frozen=True)
class HermesEndpoint:
    url: str
    api_key: str


def _read_env_file(profile_dir: Path) -> dict[str, str]:
    env_path = profile_dir / ".env"
    if not env_path.exists():
        return {}
    pairs: dict[str, str] = {}
    for line in env_path.read_text(encoding="utf-8").splitlines():
        if "=" in line and not line.lstrip().startswith("#"):
            key, value = line.split("=", 1)
            pairs[key.strip()] = value.strip()
    return pairs


def _free_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.bind((_LOOPBACK, 0))
        return int(sock.getsockname()[1])


def _port_is_free(port: int) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        return sock.connect_ex((_LOOPBACK, port)) != 0


def _kill_pid(pid: int) -> None:
    if os.name == "nt":
        subprocess.run(
            ["taskkill", "/F", "/T", "/PID", str(pid)],
            capture_output=True,
            check=False,
        )
        return
    with contextlib.suppress(ProcessLookupError, PermissionError):
        os.kill(pid, 15)


class HermesSupervisor:
    """Lifecycle manager for per-agent Hermes gateways (see module docstring)."""

    def __init__(
        self,
        root: str | Path,
        *,
        backend: str,
        hermes_bin: str = "hermes",
        docker_image: str = DEFAULT_DOCKER_IMAGE,
        docker_network: str = DEFAULT_DOCKER_NETWORK,
        startup_timeout: float = 120.0,
    ) -> None:
        if backend not in BACKENDS:
            raise ValueError(f"unknown Hermes backend {backend!r}; expected one of {BACKENDS}")
        self.root = Path(root)
        self.backend = backend
        self.hermes_bin = hermes_bin
        self.docker_image = docker_image
        self.docker_network = docker_network
        self.startup_timeout = startup_timeout
        self._processes: dict[str, subprocess.Popen[bytes]] = {}
        self._errors: dict[str, str] = {}
        self._locks: dict[str, threading.Lock] = {}
        self._guard = threading.Lock()

    @classmethod
    def from_env(cls, storage_root: str | Path) -> HermesSupervisor | None:
        """Supervisor configured by ``GENERAL_CHAT_HERMES_*``; ``None`` when not enabled."""
        backend = os.getenv("GENERAL_CHAT_HERMES_BACKEND", "").strip().lower()
        if not backend:
            return None
        return cls(
            Path(storage_root) / "hermes",
            backend=backend,
            hermes_bin=os.getenv("GENERAL_CHAT_HERMES_BIN", "").strip() or "hermes",
            docker_image=os.getenv("GENERAL_CHAT_HERMES_IMAGE", "").strip() or DEFAULT_DOCKER_IMAGE,
            docker_network=os.getenv("GENERAL_CHAT_HERMES_NETWORK", "").strip()
            or DEFAULT_DOCKER_NETWORK,
        )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def profile_dir(self, agent_id: str) -> Path:
        return self.root / agent_id

    def ensure(self, spec: HermesProfileSpec, env: dict[str, str]) -> HermesEndpoint:
        """Render ``spec``, make sure its gateway runs with that exact render, return its endpoint.

        Args:
            spec: The agent's profile spec (``port``/``host`` are chosen here).
            env: Secret environment for the gateway (LLM key, MCP secrets).
        """
        validate_spec(spec)
        with self._lock_for(spec.agent_id):
            try:
                endpoint = self._ensure_locked(spec, env)
            except Exception as exc:
                self._errors[spec.agent_id] = str(exc)
                raise
            self._errors.pop(spec.agent_id, None)
            return endpoint

    def stop(self, agent_id: str) -> None:
        with self._lock_for(agent_id):
            self._stop_locked(agent_id)

    def remove(self, agent_id: str) -> None:
        """Stop the gateway and delete the agent's Hermes profile (memories, sessions, keys)."""
        with self._lock_for(agent_id):
            self._stop_locked(agent_id)
            shutil.rmtree(self.profile_dir(agent_id), ignore_errors=True)
            self._errors.pop(agent_id, None)

    def shutdown(self) -> None:
        """Stop child processes started by this supervisor.

        Containers are left running on purpose: they survive an API
        container restart and are adopted again by the next ``ensure``.
        """
        if self.backend != BACKEND_PROCESS:
            return
        for agent_id in list(self._processes):
            with contextlib.suppress(Exception):
                self.stop(agent_id)

    def status(self, agent_id: str) -> dict[str, Any]:
        profile_dir = self.profile_dir(agent_id)
        env = _read_env_file(profile_dir)
        rendered = (profile_dir / "config.yaml").is_file()
        url = self._url(agent_id, env) if rendered else ""
        toolsets: list[str] = []
        healthy = bool(url) and self._healthy(url)
        if healthy:
            toolsets = self._enabled_toolsets(url, env.get("API_SERVER_KEY", ""))
        return {
            "backend": self.backend,
            "rendered": rendered,
            "running": healthy,
            "url": url,
            "enabledToolsets": toolsets,
            "error": self._errors.get(agent_id, ""),
        }

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    def _lock_for(self, agent_id: str) -> threading.Lock:
        with self._guard:
            return self._locks.setdefault(agent_id, threading.Lock())

    def _ensure_locked(self, spec: HermesProfileSpec, env: dict[str, str]) -> HermesEndpoint:
        profile_dir = self.profile_dir(spec.agent_id)
        existing = _read_env_file(profile_dir)
        if self.backend == BACKEND_DOCKER:
            spec.host, spec.port = CONTAINER_API_HOST, DEFAULT_API_PORT
        else:
            spec.host = _LOOPBACK
            previous = int(existing.get("API_SERVER_PORT") or 0)
            was_running = bool(previous) and self._healthy(f"http://{_LOOPBACK}:{previous}")
            spec.port = previous if previous and (was_running or _port_is_free(previous)) else 0
            spec.port = spec.port or _free_port()

        before = self._stored_hash(profile_dir)
        write_profile(self.root, spec, llm_key_slot=False)
        after = self._render_hash(profile_dir, env)
        file_env = _read_env_file(profile_dir)
        url = self._url(spec.agent_id, file_env)
        api_key = file_env.get("API_SERVER_KEY", "")
        if not api_key:
            raise HermesSupervisorError(f"agent {spec.agent_id!r}: profile has no API_SERVER_KEY")

        if before == after and self._healthy(url):
            return HermesEndpoint(url, api_key)
        self._stop_locked(spec.agent_id)
        self._start(spec.agent_id, profile_dir, env)
        self._wait_healthy(spec.agent_id, url)
        (profile_dir / RENDER_HASH_FILE).write_text(after, encoding="utf-8")
        return HermesEndpoint(url, api_key)

    def _url(self, agent_id: str, env: dict[str, str]) -> str:
        if self.backend == BACKEND_DOCKER:
            return f"http://{self._container_name(agent_id)}:{DEFAULT_API_PORT}"
        port = env.get("API_SERVER_PORT", "")
        return f"http://{_LOOPBACK}:{port}" if port else ""

    @staticmethod
    def _container_name(agent_id: str) -> str:
        return f"hermes-{agent_id}"

    @staticmethod
    def _render_hash(profile_dir: Path, env: dict[str, str]) -> str:
        """Digest of everything a restart must pick up (secret values hashed, never stored)."""
        digest = hashlib.sha256()
        for name in ("config.yaml", "SOUL.md"):
            digest.update((profile_dir / name).read_bytes())
        for key in sorted(env):
            digest.update(f"{key}={env[key]}\n".encode())
        return digest.hexdigest()

    @staticmethod
    def _stored_hash(profile_dir: Path) -> str:
        path = profile_dir / RENDER_HASH_FILE
        return path.read_text(encoding="utf-8").strip() if path.exists() else ""

    @staticmethod
    def _healthy(url: str) -> bool:
        try:
            return requests.get(f"{url}/health", timeout=3.0).status_code == 200
        except requests.RequestException:
            return False

    @staticmethod
    def _enabled_toolsets(url: str, api_key: str) -> list[str]:
        try:
            response = requests.get(
                f"{url}/v1/toolsets", headers={"Authorization": f"Bearer {api_key}"}, timeout=10.0
            )
            data = response.json().get("data") if response.status_code == 200 else None
        except (requests.RequestException, ValueError):
            return []
        return sorted(str(item.get("name")) for item in data or [] if item.get("enabled"))

    def _wait_healthy(self, agent_id: str, url: str) -> None:
        deadline = time.monotonic() + self.startup_timeout
        while time.monotonic() < deadline:
            if self._healthy(url):
                return
            process = self._processes.get(agent_id)
            if process is not None and process.poll() is not None:
                raise HermesSupervisorError(
                    f"agent {agent_id!r}: Hermes gateway exited with code {process.returncode} "
                    f"(see {self.profile_dir(agent_id) / 'logs'})"
                )
            time.sleep(1.0)
        self._stop_locked(agent_id)
        raise HermesSupervisorError(
            f"agent {agent_id!r}: Hermes gateway not healthy after {self.startup_timeout:.0f}s"
        )

    def _start(self, agent_id: str, profile_dir: Path, env: dict[str, str]) -> None:
        if self.backend == BACKEND_DOCKER:
            self._start_container(agent_id, profile_dir, env)
        else:
            self._start_process(agent_id, profile_dir, env)

    def _start_process(self, agent_id: str, profile_dir: Path, env: dict[str, str]) -> None:
        child_env = {
            **os.environ,
            **env,
            "HERMES_HOME": str(profile_dir.resolve()),
            "PYTHONUTF8": "1",
        }
        (profile_dir / "logs").mkdir(parents=True, exist_ok=True)
        log = (profile_dir / "logs" / "sss-gateway.log").open("ab")
        try:
            self._processes[agent_id] = subprocess.Popen(
                [self.hermes_bin, "gateway", "run"],
                env=child_env,
                cwd=str(profile_dir / "workspace"),
                stdout=log,
                stderr=subprocess.STDOUT,
                stdin=subprocess.DEVNULL,
            )
        except OSError as exc:
            raise HermesSupervisorError(
                f"cannot start Hermes ({self.hermes_bin!r}): {exc}. "
                "Set GENERAL_CHAT_HERMES_BIN to the hermes executable."
            ) from exc
        finally:
            log.close()

    def _start_container(self, agent_id: str, profile_dir: Path, env: dict[str, str]) -> None:
        name = self._container_name(agent_id)
        command = [
            "docker",
            "run",
            "-d",
            "--name",
            name,
            "--restart",
            "unless-stopped",
            "--network",
            self.docker_network,
            "--network-alias",
            name,
            "--memory",
            "1g",
            "--cpus",
            "1",
            "--pids-limit",
            "256",
            "--security-opt",
            "no-new-privileges:true",
            # Same path inside and outside the API container (compose convention),
            # so this is a valid *host* path for the sibling container's bind mount.
            "-v",
            f"{profile_dir.resolve()}:/opt/data",
        ]
        for key in sorted(env):
            command += ["-e", key]  # value comes from our environment, never argv
        command += [self.docker_image, "gateway", "run"]
        try:
            result = subprocess.run(
                command,
                env={**os.environ, **env},
                capture_output=True,
                text=True,
                timeout=120,
                check=False,
            )
        except (OSError, subprocess.TimeoutExpired) as exc:
            raise HermesSupervisorError(f"docker run failed for {name}: {exc}") from exc
        if result.returncode != 0:
            raise HermesSupervisorError(
                f"docker run failed for {name}: {result.stderr.strip()[:300]}"
            )

    def _stop_locked(self, agent_id: str) -> None:
        if self.backend == BACKEND_DOCKER:
            with contextlib.suppress(OSError, subprocess.TimeoutExpired):
                subprocess.run(
                    ["docker", "rm", "-f", self._container_name(agent_id)],
                    capture_output=True,
                    timeout=60,
                    check=False,
                )
            return
        process = self._processes.pop(agent_id, None)
        if process is not None and process.poll() is None:
            _kill_pid(process.pid)
            with contextlib.suppress(subprocess.TimeoutExpired):
                process.wait(timeout=15)
        # A gateway adopted from a previous run has no Popen handle — use its pid file.
        pid_file = self.profile_dir(agent_id) / "gateway.pid"
        if pid_file.exists():
            raw = pid_file.read_text(encoding="utf-8").strip()
            with contextlib.suppress(ValueError, TypeError, AttributeError):
                pid = json.loads(raw).get("pid") if raw.startswith("{") else int(raw)
                if pid:
                    _kill_pid(int(pid))
