-- Business schema + base seed for the db_server MCP (Cloud SQL Postgres, appdata).
--
-- Run `deploy.sh init-appdb` first (creates appdata + mart + mcp_app), then:
--     bash deploy/deploy.sh seed-mcp-db deploy/appdb/init.sql
--
-- Idempotent: drops + recreates the public business tables so re-seeding is clean.
-- Applied as the admin role; grants read to mcp_app at the end.

DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE products (
    id       integer PRIMARY KEY,
    name     text    NOT NULL,
    category text    NOT NULL,
    price    numeric(10, 2) NOT NULL,
    in_stock boolean NOT NULL DEFAULT true
);

INSERT INTO products (id, name, category, price, in_stock) VALUES
    (1, 'Aeron Chair',         'furniture',   1395.00, true),
    (2, 'Standing Desk',       'furniture',    699.00, true),
    (3, 'Mechanical Keyboard', 'electronics',  129.99, true),
    (4, '4K Monitor',          'electronics',  449.00, false),
    (5, 'Desk Lamp',           'lighting',      59.50, true);

CREATE TABLE users (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       text NOT NULL,
    email      text UNIQUE NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO users (id, name, email) VALUES
    (1, 'Alice Tan',    'alice@example.com'),
    (2, 'Budi Santoso', 'budi@example.com'),
    (3, 'Carla Wijaya', 'carla@example.com');

CREATE TABLE orders (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      integer REFERENCES users(id),
    product_id   integer REFERENCES products(id),
    quantity     integer NOT NULL DEFAULT 1,
    status       text NOT NULL,
    total_amount numeric(10, 2) NOT NULL,
    ordered_at   timestamptz NOT NULL DEFAULT now()
);

INSERT INTO orders (user_id, product_id, quantity, status, total_amount, ordered_at) VALUES
    (1, 1, 2, 'paid',      2790.00, '2026-06-01'),
    (1, 3, 5, 'pending',    649.95, '2026-06-03'),
    (2, 5, 1, 'paid',        59.50, '2026-06-07'),
    (3, 2, 1, 'cancelled',  699.00, '2026-06-09');

-- Let the MCP role read the freshly created tables.
GRANT SELECT ON ALL TABLES IN SCHEMA public TO mcp_app;
